[project]
name = "KernelModeDecomposition1D"
version = "1.0.0"

requires-python = ">=3.7"
dependencies = [
  "matplotlib",
  "numpy",
  "scipy",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["."]
